export class LoggerConstant{
    public static readonly CreateInventoryController = "Creation Inventory Initiated in controller"
    public static readonly createInventoryDone = "Create Inventory Done in controller"
    public static readonly createInventoryError = "Create Inventory Error in controller"
    public static readonly getInventorys = "Get Inventory initialized"
    public static readonly getInventorysDone = "Get Inventory Done in controller"
    public static readonly getInventorysError = "Get Inventory Error in controller"
    public static readonly getOneInventorys = "Get One Inventory Initialized in controller"
    public static readonly getOneInventorysDone = "Get One Inventory Done in controller"
    public static readonly getOneInventorysError = "Get One Inventory Error in controller"
    public static readonly updateOneInventorys = "Update One Inventory Initialized in controller"
    public static readonly updateOneInventorysDone = "Update One Inventory Done in controller"
    public static readonly updateOneInventorysError = "Update One Inventory Error in Controller"
    public static readonly deleteInventorys = "Delete Inventory Initialized in controller"
    public static readonly deleteInventorysDone = "Delete Inventory Done in Controller"
    public static readonly deleteInventorysError = "Delete Inventory Error in Controller"

    //Service Loggers Inventorys
    public static readonly CreateInventoryService = "Creation Inventory Initiated in service"
    public static readonly createInventoryDoneService = "Create Inventory Done in service"
    public static readonly createInventoryErrorService = "Create Inventory Error in service"
    public static readonly getInventorysService = "Get Inventory initialized"
    public static readonly getInventorysDoneService = "Get Inventory Done in service"
    public static readonly getInventorysErrorService = "Get Inventory Error in service"
    public static readonly getOneInventorysService = "Get One Inventory Initialized in service"
    public static readonly getOneInventorysDoneService = "Get One Inventory Done in service"
    public static readonly getOneInventorysErrorService = "Get One Inventory Error in service"
    public static readonly updateOneInventorysService = "Update One Inventory Initialized in service"
    public static readonly updateOneInventorysDoneService = "Update One Inventory Done in service"
    public static readonly updateOneInventorysErrorService = "Update One Inventory Error in service"
    public static readonly deleteInventorysService = "Delete Inventory Initialized in service"
    public static readonly deleteInventorysDoneService = "Delete Inventory Done in service"
    public static readonly deleteInventorysErrorService = "Delete Inventory Error in service"

    //Dao Loggers Inventory
    public static readonly CreateInventoryDao = "Creation Inventory Initiated in Dao"
    public static readonly createInventoryDoneDao = "Create Inventory Done in Dao"
    public static readonly createInventoryErrorDao = "Create Inventory Error in Dao"
    public static readonly getInventorysDao = "Get Inventory initialized"
    public static readonly getInventorysDoneDao = "Get Inventory Done in Dao"
    public static readonly getInventorysErrorDao = "Get Inventory Error in Dao"
    public static readonly getOneInventorysDao = "Get One Inventory Initialized in Dao"
    public static readonly getOneInventorysDoneDao = "Get One Inventory Done in Dao"
    public static readonly getOneInventorysErrorDao = "Get One Inventory Error in Dao"
    public static readonly updateOneInventorysDao = "Update One Inventory Initialized in Dao"
    public static readonly updateOneInventorysDoneDao = "Update One Inventory Done in Dao"
    public static readonly updateOneInventorysErrorDao = "Update One Inventory Error in Dao"
    public static readonly deleteInventorysDao = "Delete Inventory Initialized in Dao"
    public static readonly deleteInventorysDoneDao = "Delete Inventory Done in Dao"
    public static readonly deleteInventorysErrorDao = "Delete Inventory Error in Dao"
}